services:
  - type: web
    name: agroconnect-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        value: https://ycorozkbfeqwybujwnaz.supabase.co
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://your-frontend-domain.com
